/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.6
// source: proto/google_drive.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./google_drive_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.GoogleDriveGrpcSyncClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.GoogleDriveGrpcSyncPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SyncFilesRequest,
 *   !proto.SyncFilesResponse>}
 */
const methodDescriptor_GoogleDriveGrpcSync_SyncFiles = new grpc.web.MethodDescriptor(
  '/GoogleDriveGrpcSync/SyncFiles',
  grpc.web.MethodType.UNARY,
  proto.SyncFilesRequest,
  proto.SyncFilesResponse,
  /**
   * @param {!proto.SyncFilesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SyncFilesResponse.deserializeBinary
);


/**
 * @param {!proto.SyncFilesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SyncFilesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SyncFilesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.GoogleDriveGrpcSyncClient.prototype.syncFiles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/GoogleDriveGrpcSync/SyncFiles',
      request,
      metadata || {},
      methodDescriptor_GoogleDriveGrpcSync_SyncFiles,
      callback);
};


/**
 * @param {!proto.SyncFilesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SyncFilesResponse>}
 *     Promise that resolves to the response
 */
proto.GoogleDriveGrpcSyncPromiseClient.prototype.syncFiles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/GoogleDriveGrpcSync/SyncFiles',
      request,
      metadata || {},
      methodDescriptor_GoogleDriveGrpcSync_SyncFiles);
};


module.exports = proto;

