/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.6
// source: proto/notion_sync.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./notion_sync_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.NotionSyncClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.NotionSyncPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SyncDatabaseRequest,
 *   !proto.SyncDatabaseResponse>}
 */
const methodDescriptor_NotionSync_SyncDatabase = new grpc.web.MethodDescriptor(
  '/NotionSync/SyncDatabase',
  grpc.web.MethodType.UNARY,
  proto.SyncDatabaseRequest,
  proto.SyncDatabaseResponse,
  /**
   * @param {!proto.SyncDatabaseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SyncDatabaseResponse.deserializeBinary
);


/**
 * @param {!proto.SyncDatabaseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SyncDatabaseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SyncDatabaseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.NotionSyncClient.prototype.syncDatabase =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/NotionSync/SyncDatabase',
      request,
      metadata || {},
      methodDescriptor_NotionSync_SyncDatabase,
      callback);
};


/**
 * @param {!proto.SyncDatabaseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SyncDatabaseResponse>}
 *     Promise that resolves to the response
 */
proto.NotionSyncPromiseClient.prototype.syncDatabase =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/NotionSync/SyncDatabase',
      request,
      metadata || {},
      methodDescriptor_NotionSync_SyncDatabase);
};


module.exports = proto;

