name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19.4.0

      - name: Install Dependencies
        run: yarn install --legacy-peer-deps

      - name: Build
        run: yarn build

  # test-macos:
  #   runs-on: macos-latest
  #   needs: build
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 19.4.0

  #     - name: Install Dependencies
  #       run: yarn install

  #     - name: Run Unit Tests on macOS
  #       run: yarn test:unit

  # test-windows:
  #   runs-on: windows-latest
  #   needs: build
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 19.4.0

  #     - name: Install Dependencies
  #       run: yarn install

  #     - name: Run Unit Tests on Windows
  #       run: yarn test:unit
